config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get("/", { to: "ideas#index", as: :root })

  resources :users
  resource :session, only: [:new, :create, :destroy]
  resources :ideas do
    get :liked, on: :collection
    resources :likes, shallow: true, only: [:create, :destroy]
    resources :reviews, shallow: true, only: [:create, :destroy] do
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # guest user (not logged in)

    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    alias_action(:create, :read, :update, :delete, to: :crud)
    can(:crud, Idea) do |idea|
      user == idea.user
    end

    can(:crud, Review) do |review|
      review.user == user
    end
    can(:destroy, Like) do |like|
      like.user == user
    end
    can :like, Idea do |idea|
      user.persisted?
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  has_many :reviews, dependent: :destroy
  belongs_to :user, optional: true
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user
  before_save :capitalize_title

  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :description, presence: true

  private

  def capitalize_title
    self.title.capitalize!
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :idea

  validates(
    :idea_id,
    uniqueness: {
      scope: :user_id,
      message: "has already been liked",
    },
  )
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :idea
end

app/models/user.rb
class User < ApplicationRecord
  has_many :ideas, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_ideas, through: :likes, source: :idea

  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }

  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}".titleize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def current_user
    @current_user ||= User.find_by_id session[:user_id]
  end

  helper_method(:current_user)

  def user_signed_in?
    current_user.present?
  end

  helper_method :user_signed_in?

  def authenticate_user!
    redirect_to new_session_path, notice: "Please sign in" unless user_signed_in?
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :find_idea, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @ideas = Idea.order(created_at: :desc)
  end

  def new
    @idea = Idea.new
  end

  def show
    @reviews = @idea.reviews.order(created_at: :desc)
    @idea = Idea.find params[:id]
    @review = Review.new
    @like = @idea.likes.find_by(user: current_user)
  end

  def create
    @idea = Idea.new idea_params
    @idea.user = current_user
    if @idea.save
      flash[:notice] = "Idea posted successfully"
      redirect_to idea_path(@idea.id)
    else
      render :new
    end
  end

  def update
    if @idea.update idea_params
      redirect_to idea_path(@idea.id), notice: "Idea updated successfully"
    else
      render :edit
    end
  end

  def edit
  end

  def destroy
    @idea.destroy
    redirect_to ideas_path, alert: "Idea deleted"
  end

  private

  def find_idea
    @idea = Idea.find params[:id]
  end

  def idea_params
    params.require(:idea).permit(:title, :description)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :find_idea, only: [:create]

  def create
    like = Like.new(user: current_user, idea: @idea)

    if like.save
      flash[:success] = "Idea Liked"
    else
      flash[:danger] = like.errors.full_messages.join(", ")
    end

    redirect_to ideas_path
  end

  def destroy
    like = current_user.likes.find params[:id]

    if can? :destroy, like
      like.destroy
      flash[:success] = "Idea Unliked"
    else
      flash[:alert] = "Can't Unlike!"
    end
    redirect_to ideas_path
  end

  private

  def find_idea
    @idea = Idea.find params[:idea_id]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def new
    @review = Review.new
  end

  def create
    @idea = Idea.find params[:idea_id]
    @review = Review.new review_params
    @review.idea = @idea
    @review.user = current_user
    if @review.save
      redirect_to idea_path(@idea), notice: "review posted"
    else
      @review = @idea.reviews.order(created_at: :desc)
      render "/ideas/show"
    end
  end

  def destroy
    @review = Review.find params[:format]
    @review.destroy
    redirect_to idea_path(@review.idea), notice: "review deleted"
  end

  private

  def review_params
    params.require(:review).permit(:body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to ideas_path, notice: "#{@user.full_name} successfully signed in!"
    else
      flash[:alert] = "Wrong email or password."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged Out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :user_signed_in?, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to ideas_path, notice: "#{@user.full_name} successfully signed up!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to root_path
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
              <%= render "shared/errors", obj: @idea %>
            <%= form_with(model: @idea, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |form| %>
            <div class="form-group row">
                    <%= form.label :title, class: "col-2 col-form-label text-light" %>
                        <div class="col-10">
                            <%= form.text_field :title, class: "form-control shadow rounded", placeholder: "Idea title" %>
                        </div>
                    </div>
                        <div class="form-group row">
                        <%= form.label :description, class: "col-2 col-form-label text-light" %>
                            <div class="col-10">
                                <%= form.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "What's your big idea?" %>
                            </div>
                        </div>
                    <div> 
                </div> 
                <div class="form-group row justify-content-center">
                <%= form.submit class: "btn btn-outline-light btn-lg" %>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/ideas/edit.html.erb
<h1 class="text-center mt-4">Edit Idea</h1>
<%= render "form" %> 

app/views/ideas/index.html.erb
<h1 class="text-center mt-4">All Ideas</h1>
<div class="container">
    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 justify-content-md-center">
  <% @ideas.each do |idea| %>
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
                 <div class="card-header">
                    Idea by: <%= idea.user&.full_name || "Deleted" %>
                </div>
        <div class="card-body">
                <h5 class="card-title">
                  <%= link_to(idea.title, idea_path(idea.id)) %>
</h5>
          <p class="card-text"><%= idea.description %></p>
                  <p class="card-text"><%= idea.likes.count %> likes</p>                                          
   <% like = idea.likes.find_by(user: current_user) %>
        <% if like.present? && can?(:destroy, like) %>
            <%= link_to(
                  "Liked",
                  like_path(like),
                  class: "btn btn-outline-danger",
                  method: :delete,
                ) %> 
        <% elsif can?(:like, idea) %>
            <%= link_to(
                  "Like",
                  idea_likes_path(idea),
                  class: "btn btn-outline-info",
                  method: :post,
                ) %> 
        <% end %>
        <div class="card-footer text-muted mt-3">
                    <small>Posted <%= time_ago_in_words(idea.created_at) %> ago</small>
                </div>
      </div>
      </div>
    </div>
  <% end %>
   </div>
</div>

app/views/ideas/new.html.erb
<h1 class="text-center mt-4">Share your Idea</h1>
<%= render "form" %> 

app/views/ideas/show.html.erb
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
            <div class="card text-center shadow mb-7 bg-white rounded">
                <div class="card-header">
                    Idea by: <%= @idea.user&.full_name || "Deleted" %>
                </div>
                <div class="card-body">
                    <h5 class="card-title">
                        <%= @idea.title %>
                    </h5>
                    <p class="card-text">
                        <%= @idea.description %>
                    </p> 
                            <div>
                        <small>
                            <%= @idea.likes.count %> likes
                        </small>
                    </div>
                        <% if can? :crud, @idea %>
                        <%= link_to "Delete", idea_path(@idea), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?" } %>
                        <%= link_to "Edit", edit_idea_path(@idea), class: "btn btn-outline-info" %>
                        <% end %>
                
                    <div class="card-footer mt-2 text-muted">
                        <small>posted    <%= time_ago_in_words(@idea.created_at) %> ago</small>
                    </div>
                </div>
            </div>    
                <div class="card text-center shadow mt-4 mb-5 bg-white rounded">
                    <div class="card-header">
Post a review
                    </div>
                        <%= form_with model: [@idea, @review], class: "shadow p-3 mb-3 bg-info rounded", local: true do |f| %>
                        <%= render "shared/errors", obj: @review %>
                    <div class='shadow-sm p-3 mb-5 round'>
                        <%= f.text_area :body,
                                        cols: 50,
                                        rows: 5,
                                        placeholder: "What do you think?" %>
                    </div>
                       <%= f.submit class: "btn btn-primary" %>
                        <% end %>
                </div>        
                    <h3 class= "text-center">reviews</h3>
                        <% @reviews.each do |review| %>
            <div class="card text-center shadow mt-4 mb-5 bg-white rounded">
                    <h5 class="card-title">reviewed <%= time_ago_in_words(review.created_at) %> ago by <%= review.user.full_name %></h5>
                    <p class="card-text"><%= review.body %></p>
                        <% if can? :crud, review %>
                        <%= link_to "Delete", review_path(@idea, review), method: :delete, data: { confirm: "Are you sure?" } %>
                        <% end %>                
            </div>
                <% end %>        
        </div>
    </div>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Blog on Rails", root_path, class: "navbar-brand mb-0 h1" %>
    <ul class="navbar-nav mr-auto">
      <%= link_to "New Idea", new_idea_path, class: "nav-link" %>
       <% if !user_signed_in? %>
      <%= link_to "Sign up", new_user_path, class: "nav-link" %>
      <%= link_to "Sign in", new_session_path, class: "nav-link" %>
      <% end %>
          <% if user_signed_in? %>

      <%= link_to(current_user.full_name, edit_user_path(current_user), class: "nav-link") %>


      <%= link_to "Sign Out", session_path, method: :delete,
                                            data: { confirm: "Are you sure you want to sign out?" }, class: "nav-link" %>
      <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Quiz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_pack_tag "application" %>
  </head>

  <body>
     <div class='d-flex flex-column'>
      <%= render "layouts/navbar" %>
      <%= render "layouts/messages" %>
    <%= yield %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render "shared/errors", obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
     
     <div class="form-group row">
          <%= f.label :first_name, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :first_name, class: "form-control shadow rounded", placeholder: "Enter your first name", :required => true %>
          </div>
        </div>
     <div class="form-group row">
          <%= f.label :last_name, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :last_name, class: "form-control shadow rounded", placeholder: "Enter your last name", :required => true %>
          </div>
        </div>


        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address", :required => true %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Enter a password", :required => true %>
          </div>
        </div>

     <div class="form-group row">
          <%= f.label :password_confirmation, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.password_field :password_confirmation, class: "form-control shadow rounded", placeholder: "Confirm your password", :required => true %>
          </div>
        </div>


        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to "[ Cancel and return to ideas index ]", ideas_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render "form" %>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Ideas Factory</h1>
<%= render "form" %>